# Generated by Django 5.2.4 on 2025-08-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название камеры')),
                ('camera_type', models.CharField(choices=[('usb', 'USB Камера'), ('ip', 'IP Камера')], max_length=10, verbose_name='Тип камеры')),
                ('source', models.CharField(max_length=200, verbose_name='Источник (индекс или URL)')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
                'ordering': ['-created_at'],
            },
        ),
    ]
