version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: schooldb_control
    environment:
      POSTGRES_USER: schooluser
      POSTGRES_PASSWORD: schoolpass
      POSTGRES_DB: schooldb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shop_network

  adminer:
    image: adminer:latest
    container_name: schooldb_adminer
    ports:
      - "8080:8080"
    networks:
      - shop_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  shop_network:
    driver: bridge