version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: schooluser
      POSTGRES_PASSWORD: schoolpass
      POSTGRES_DB: schooldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: